-- Banco de dados para as confirmações do convite
-- A integração será feita na próxima etapa.

create table if not exists public.confirmacoes (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text not null,
  presenca text not null check (presenca in ('Sim', 'Não')),
  acompanhantes integer not null default 0
    check (acompanhantes between 0 and 4),
  criado_em timestamptz not null default now()
);

alter table public.confirmacoes enable row level security;

create policy "Permitir confirmação pública"
on public.confirmacoes
for insert
to anon
with check (
  char_length(trim(nome)) between 2 and 120
  and char_length(trim(telefone)) between 10 and 20
  and presenca in ('Sim', 'Não')
  and acompanhantes between 0 and 4
);
